name: circular_chart_flutter
description: Animated radial and pie charts for Flutter
version: 0.0.2
homepage: https://github.com/afandiyusuf/flutter_circular_chart

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: any

environment:
  sdk: '>=2.12.0 <3.0.0'
